
// Use the GoogleGenAI SDK to interact with Gemini models
import { GoogleGenAI } from "@google/genai";

// Directly use process.env.API_KEY as per the guidelines
const getAI = () => new GoogleGenAI({ apiKey: process.env.API_KEY });

export const editImageWithAI = async (base64Image: string, prompt: string): Promise<string> => {
  const ai = getAI();
  
  const base64Data = base64Image.split(',')[1] || base64Image;
  const mimeType = base64Image.split(';')[0].split(':')[1] || 'image/jpeg';

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Data,
              mimeType: mimeType,
            },
          },
          {
            text: `ACT AS A WORLD-CLASS PROFESSIONAL PHOTOGRAPHER AND RETOUCHER.
            
            USER REQUEST: ${prompt}.
            
            STRICT TECHNICAL SPECIFICATIONS:
            1. ASPECT RATIO & SHAPE: DO NOT alter the physical proportions of the face. DO NOT make the face thinner or wider. The subject's shape must remain EXACTLY as it is in the original photo. No distortion allowed.
            2. RESOLUTION: Enhance to 4K ultra-high resolution. Make skin, hair, and eyes extremely sharp and clear.
            3. BACKGROUND: Replace with a PERFECT SOLID PROFESSIONAL BLUE (Hex: #0047AB). 
            4. LIGHTING: Keep it natural but professional. Even studio lighting without altering face geometry.
            5. COMPOSITION: Professional passport alignment. Minimize headspace above the head.
            
            CRITICAL: The person must look exactly like themselves. No "slimming" filters. Just 4K quality and background removal.
            
            Return ONLY the final processed image.`,
          },
        ],
      },
    });

    // Iterate through response parts to find the image data
    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
      }
    }
    
    throw new Error("No image was generated by the AI.");
  } catch (error) {
    console.error("Gemini AI Error:", error);
    throw error;
  }
};
