
// Use the GoogleGenAI SDK to interact with Gemini models
import { GoogleGenAI } from "@google/genai";

// Directly use process.env.API_KEY as per the guidelines
const getAI = () => new GoogleGenAI({ apiKey: process.env.API_KEY });

export const editImageWithAI = async (base64Image: string, prompt: string): Promise<string> => {
  const ai = getAI();
  
  const base64Data = base64Image.split(',')[1] || base64Image;
  const mimeType = base64Image.split(';')[0].split(':')[1] || 'image/jpeg';

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Data,
              mimeType: mimeType,
            },
          },
          {
            text: `ACT AS A WORLD-CLASS PROFESSIONAL PHOTOGRAPHER AND RETOUCHER.
            
            Instruction: ${prompt}.
            
            STRICT TECHNICAL SPECIFICATIONS:
            1. RESOLUTION: Generate a high-quality, high-resolution output. Ensure skin textures, hair, and eyes are sharp and highly detailed.
            2. BACKGROUND: Replace current background with a PERFECT SOLID PROFESSIONAL BLUE (Hex: #0047AB). No gradients, no shadows on background.
            3. LIGHTING: Apply professional studio lighting (three-point lighting setup). Soften shadows on the face, ensure even brightness across forehead and cheeks.
            4. COMPOSITION: Front-facing, eyes exactly on the horizontal center line, neutral expression, mouth closed. Crop to a standard 35mm x 45mm portrait.
            5. COLOR: Accurate skin tones, vibrant but realistic colors, 300 DPI print-ready quality.
            
            Return ONLY the final processed image.`,
          },
        ],
      },
      config: {
        // High quality generation defaults
      }
    });

    // Iterate through response parts to find the image data
    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
      }
    }
    
    throw new Error("No image was generated by the AI.");
  } catch (error) {
    console.error("Gemini AI Error:", error);
    throw error;
  }
};
